### ISSUE TITLE
Arduino 1.5+

### ISSUE THREAD

**Issue by jgillick** [MichaelJonker/HardwareSerialRS485#1]
I'm using Arduino 1.5.8 and I get the following error when I try to compile:

```
~/Documents/Arduino/libraries/HardwareSerial_RS485/HardwareSerial_USB.cpp:21:22: 
fatal error: Platform.h: No such file or directory #include "Platform.h"
```

However, the same code seems to compile without an issue on Arduino 1.0.

**Comment by MichaelJonker** [comment]
oops sorry for the delay, my answer got lost apparently

Thanks for trying this code and reporting the issue.
I developed the code with IDE 1.0.5. The file Platform.h file must have been (re)moved since I guess.

However, this file is only included by HardwareSerial_USB.cpp, a nonfunctional development stub for ATmega32u4 based Arduini (Leonardo, micro). If you are using a UNO, you can remove the file I think.

I will pick up development in a month or so and look at the Platform.h and IDE 1.6 compatibility and ATmega32u4 based versions.

Cheers
Michael

**Comment by jgillick** [comment]
Hi Michael. Thanks for the reply. Compiling with Arduino 1.0 is working well for now. Thanks for writing this great library! I'll be honest, some of the lower level stuff is a bit over my head, but I've been going through it anyways to understand how it works. I'd love to contribute where I can and potentially help create a simplified demo (I'm working on one right now to prototype basic communication).

I am having a few small issues and questions around addressing collision detection/testing and the RE/DE pins being reset after sending, but I'll keep those until you have more time.

Lastly, and most importantly, how can I contribute to your beer fund? 

Cheers,
Jeremy

**Comment by MichaelJonker** [comment]
Hello, you may be interested that I have released a new version of the RS485 support for Arduino, This version, besides being more stable, has also a few new features.

To be compliant with the Arduino Librarian, the repository has been moved to a new place: https://github.com/MichaelJonker/HardwareSerialRS485

Please let me know if you find any problems.

Cheers

M
